# Generated by Django 5.1.1 on 2024-10-06 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
