# Generated by Django 5.1.1 on 2024-10-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_first_name_author_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='author_name',
        ),
    ]
