# Generated by Django 5.1.1 on 2024-10-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_full_name_author_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='bio',
        ),
    ]
